import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { NewsletterProvider } from "@/contexts/newsletterContext";
import { UserProvider } from "@/contexts/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen mx-auto antialiased">
        <UserProvider>
          <NewsletterProvider>
            <main className="flex-grow">
              <NavBar />
              {children}
            </main>
          </NewsletterProvider>
        </UserProvider>
      </body>
    </html>
  );
}
